Layout/LineLength:
  Max: 198

Lint/UselessAssignment:
  Exclude:
    - 'spec/models/bookmark_spec.rb'
    - 'spec/models/like_spec.rb'
    - 'spec/models/review_feedback_option_spec.rb'
    - 'spec/models/review_genre_spec.rb'
    - 'spec/models/review_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/system/bookmarks_spec.rb'
    - 'spec/system/likes_spec.rb'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 128

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
